# Generated by Django 5.2.7 on 2025-10-31 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('survey_created', 'Survey Created'), ('survey_published', 'Survey Published'), ('survey_closed', 'Survey Closed'), ('response_started', 'Response Started'), ('response_submitted', 'Response Submitted'), ('user_registered', 'User Registered'), ('user_login', 'User Login')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_answers', models.IntegerField(default=0)),
                ('most_common_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_rating', models.IntegerField(blank=True, null=True)),
                ('max_rating', models.IntegerField(blank=True, null=True)),
                ('word_count_average', models.IntegerField(blank=True, null=True)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='surveys.question')),
            ],
            options={
                'verbose_name_plural': 'Question Analytics',
            },
        ),
        migrations.CreateModel(
            name='SurveyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_responses', models.IntegerField(default=0)),
                ('completed_responses', models.IntegerField(default=0)),
                ('average_completion_time', models.DurationField(blank=True, null=True)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='surveys.survey')),
            ],
            options={
                'verbose_name_plural': 'Survey Analytics',
            },
        ),
    ]
