# Generated by Django 5.2.7 on 2025-11-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('survey_created', 'Survey Created'), ('survey_published', 'Survey Published'), ('survey_closed', 'Survey Closed'), ('survey_started', 'Survey Started'), ('survey_submitted', 'Survey Submitted'), ('response_started', 'Response Started'), ('response_submitted', 'Response Submitted'), ('response_deleted', 'Response Deleted'), ('responses_exported', 'Responses Exported'), ('user_registered', 'User Registered'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('profile_updated', 'Profile Updated'), ('password_changed', 'Password Changed')], max_length=50),
        ),
    ]
