# Generated by Django 5.2.7 on 2025-11-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
