# Generated by Django 5.2.7 on 2025-11-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='survey_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
