# Generated by Django 5.2.7 on 2025-11-11 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('mcq', 'Multiple Choice (Single)'), ('checkbox', 'Multiple Choice (Multiple)'), ('likert', 'Likert Scale'), ('rating', 'Rating'), ('dropdown', 'Dropdown'), ('date', 'Date'), ('email', 'Email'), ('matching', 'Matching')], max_length=20),
        ),
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_item', models.CharField(max_length=255)),
                ('right_item', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_pairs', to='surveys.question')),
            ],
            options={
                'ordering': ['question', 'order'],
            },
        ),
    ]
