# Generated by Django 5.2.7 on 2025-11-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_add_matching_pairs_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='matching_pairs',
        ),
    ]
